// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPUyrqXWkG1eibFEapUQ-_7Hrp2UCGyvU',
    appId: '1:576402629154:android:91d9b39515eef74085207b',
    messagingSenderId: '576402629154',
    projectId: 'smart-watering-iot-a6306',
    databaseURL: 'https://smart-watering-iot-a6306-default-rtdb.firebaseio.com',
    storageBucket: 'smart-watering-iot-a6306.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgXe75GNmv5bNRoBSJxfSFnh5G5D7_H8I',
    appId: '1:576402629154:web:a31986c34112a23885207b',
    messagingSenderId: '576402629154',
    projectId: 'smart-watering-iot-a6306',
    authDomain: 'smart-watering-iot-a6306.firebaseapp.com',
    databaseURL: 'https://smart-watering-iot-a6306-default-rtdb.firebaseio.com',
    storageBucket: 'smart-watering-iot-a6306.firebasestorage.app',
    measurementId: 'G-DCFMYV5J98',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgXe75GNmv5bNRoBSJxfSFnh5G5D7_H8I',
    appId: '1:576402629154:web:a31986c34112a23885207b',
    messagingSenderId: '576402629154',
    projectId: 'smart-watering-iot-a6306',
    authDomain: 'smart-watering-iot-a6306.firebaseapp.com',
    databaseURL: 'https://smart-watering-iot-a6306-default-rtdb.firebaseio.com',
    storageBucket: 'smart-watering-iot-a6306.firebasestorage.app',
    measurementId: 'G-DCFMYV5J98',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR7WnJnzAFi_3Hr-eilRLncN1NTsV07yg',
    appId: '1:576402629154:ios:cfa58425f17b039585207b',
    messagingSenderId: '576402629154',
    projectId: 'smart-watering-iot-a6306',
    databaseURL: 'https://smart-watering-iot-a6306-default-rtdb.firebaseio.com',
    storageBucket: 'smart-watering-iot-a6306.firebasestorage.app',
    iosBundleId: 'com.example.smartWatering',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR7WnJnzAFi_3Hr-eilRLncN1NTsV07yg',
    appId: '1:576402629154:ios:cfa58425f17b039585207b',
    messagingSenderId: '576402629154',
    projectId: 'smart-watering-iot-a6306',
    databaseURL: 'https://smart-watering-iot-a6306-default-rtdb.firebaseio.com',
    storageBucket: 'smart-watering-iot-a6306.firebasestorage.app',
    iosBundleId: 'com.example.smartWatering',
  );

}